FROM --platform=$TARGETOS/$TARGETARCH eclipse-temurin:11-alpine

LABEL author="joshrpg" maintainer=""
LABEL org.opencontainers.image.source="https://github.com/joshrpg/images"
LABEL org.opencontainers.image.licenses=MIT
LABEL org.opencontainers.image.description "A java 11 image to be used with https://pterodactyl.io/"

RUN apk --no-cache update
RUN apk --no-cache upgrade

RUN apk --no-cache add bash

RUN adduser container --home /home/container --disabled-password
USER container
ENV USER=container HOME=/home/container
WORKDIR  /home/container

ADD ../entrypoint.sh /entrypoint.sh
CMD [ "/bin/bash", "/entrypoint.sh" ]