FROM --platform=$TARGETOS/$TARGETARCH alpine:latest

LABEL author="joshrpg" maintainer=""
LABEL org.opencontainers.image.source="https://github.com/joshrpg/images"
LABEL org.opencontainers.image.licenses=MIT
LABEL org.opencontainers.image.description="A nginx image to be used with https://pterodactyl.io/"

RUN apk --no-cache update
RUN apk --no-cache upgrade
RUN apk --no-cache add curl ca-certificates nginx-mod-rtmp

RUN adduser -D container
RUN chown container:container -R /home/container
RUN chown container:container -R /var/lib/nginx

RUN ln -sf /dev/stdout /var/log/nginx/access.log
RUN ln -sf /dev/stderr /var/log/nginx/error.log

USER container
ENV USER=container HOME=/home/container

WORKDIR /home/container

ADD ./entrypoint.sh /entrypoint.sh
COPY --chown=container:container ./entrypoint.sh /entrypoint.sh
# RUN chown container:container /entrypoint.sh
CMD ["/bin/ash", "/entrypoint.sh"]
