name: build pterodactyl app images
on:
  workflow_dispatch:
  schedule:
    - cron: '0 23 * * *'
  push:
    branches: [ "main" ]
    paths: [ "pterodactyl/apps/**"]
  pull_request:
    branches: [ "main" ]
jobs:
  push:
    name: "pterodactyl:${{ matrix.images }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        images:
          - nginx
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
        # with:
        #   buildkit-flags: --debug
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v4
        with:
          context: ./pterodactyl/apps/${{ matrix.images }}
          file: ./pterodactyl/apps/${{ matrix.images }}/dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/joshrpg/pterodactyl:${{ matrix.images }}
